### ISSUE TITLE
Launch Plex

### ISSUE THREAD

**Issue by corydorning** [tig/mcec#1]
Is it possible to use MCE Controller and the MCEControl.commands file to launch plex?

**Comment by corydorning** [comment]
Or any other Portugal for that matter

**Comment by corydorning** [comment]
Program*

**Comment by tig** [comment]
Yes. See the Wiki Documentation for the StartProcess command.

**Comment by corydorning** [comment]
Hmm...i looked through everything but couldn't quite figure it out. :/

Is this what I'd put into the command file if I wanted plex to launch when triggering `mce_start`?

`<StartProcess Cmd="mce_start" File="C:\path\to\plex.exe"></StartProcess>`

**Comment by tig** [comment]
it's been a LONG time since I've actually used/tested it, but yes that's the idea. 

You may need to encode the backslashes. 

The code is very simple. See ProcessCommands.cs in the source code.

**Comment by tig** [comment]
I just tested this MCEControl.commands file and it worked fine:

<?xml version="1.0" encoding="utf-8"?>
<MCEController xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
<Commands xmlns="http://www.kindel.com/products/mcecontroller">
   <StartProcess Cmd="mce_start" File="C:\windows\notepad.exe">
   </StartProcess>
</Commands>
</MCEController>

**Comment by tig** [comment]
I just tried this and it worked:

```
<?xml version="1.0" encoding="utf-8"?>
<MCEController xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
<Commands xmlns="http://www.kindel.com/products/mcecontroller">
   <StartProcess Cmd="notepad" File="C:\windows\notepad.exe">
   </StartProcess>
</Commands>
</MCEController>
```

**Comment by corydorning** [comment]
i'm trying this but not luck... :/

```
<?xml version="1.0" encoding="utf-8"?>
<MCEController xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
               xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
<Commands xmlns="http://www.kindel.com/products/mcecontroller">

<StartProcess Cmd="mcestart" File="C:\Program Files\Plex\Plex Media Player\PlexMediaPlayer.exe">
</StartProcess>

</Commands>
</MCEController>
```

**Comment by corydorning** [comment]
Nevermind. I got it working. My commands file was in the wrong location. Doh. Thanks! Awesome program
