### ISSUE TITLE
Control4 Driver

### ISSUE THREAD

**Issue by cpereirasp** [tig/mcec#10]
Hi Charlie,

You've mentioned you have a Control4 Driver for OS3 available upon request. Would you mind sharing it?

Thanks,

Carlos

**Comment by tig** [comment]
You bet. I put it here:

https://github.com/tig/User_Activity

The Releases section of that repo has a `.c4z` file.

Note that the CONTACT_SENSOR binding does not work. You need to just put some programming on the `Activity Detected` event.
