### ISSUE TITLE
SR260 - sending VK_ESCAPE, receive VK_END_CANCEL from EA-1

### ISSUE THREAD

**Issue by shutupdude** [tig/mcec#11]
I'm trying out setting up the escape button on my 260, and I'm hitting the circle with a strike through it, and I get the log below. Could I get some guidance?

-log-
2020-03-29 03:46:43,767 INFO  - SendInputCommand Cmd="VK_ESCAPE" Args="" Vk="VK_ESCAPE" Shift="False" Ctrl="False" Alt="False" Win="False" (vk_ESCAPE) (0x1b)
2020-03-29 03:46:43,897 INFO  - SocketServer: Received from Client #5 at 192.168.2.10:47136: VK_END_CANCEL
2020-03-29 03:46:43,912 INFO  - Commands: Unknown command: VK_END_CANCEL

**Comment by tig** [comment]
> 2020-03-29 03:46:43,767 INFO - SendInputCommand Cmd="VK_ESCAPE" Args="" Vk="VK_ESCAPE" Shift="False" Ctrl="False" Alt="False" Win="False" (vk_ESCAPE) (0x1b)

The above looks like you successfully sent `VK_ESCAPE` and it was actioned. Right?

> 2020-03-29 03:46:43,897 INFO - SocketServer: Received from Client #5 at 192.168.2.10:47136: VK_END_CANCEL
> 2020-03-29 03:46:43,912 INFO - Commands: Unknown command: VK_END_CANCEL

There's no built-in `VK_END_CANCEL` command. Thus it's Unknown. Is this really what you meant to send?

Please verify you are using the latest version (2.2.1.503). Thanks.

**Comment by shutupdude** [comment]
Hi, just checked the MCE Folder to verify that I am on version 2.2.1.503. Composer is version 3.1.2.

`VK_ESCAPE` is the desired action but for good measure I also enabled `esc`  and tried firing commands from another computer running PuTTY but still no action from the desktop computer for escape. `up` `down` `left` `right` work trough PuTTY.

`up` `down` `left` `right` work with the SR260 but the log returns with
>2020-03-29 13:39:54,697 INFO  - SocketServer: Received from Client #6 at 192.168.2.10:40396: VK_UP
2020-03-29 13:39:54,712 INFO  - SendInputCommand Cmd="VK_UP" Args="" Vk="VK_UP" Shift="False" Ctrl="False" Alt="False" Win="False" (vk_UP) (0x26)
2020-03-29 13:39:54,837 INFO  - SocketServer: Received from Client #6 at 192.168.2.10:40396: VK_END_UP
2020-03-29 13:39:54,837 INFO  - Commands: Unknown command: VK_END_UP

To me it looks like I'm getting responses back from the EA1 and are strange VK codes, as I've never seen `VK_END_UP` or `VK_END_CANCEL`

**Comment by tig** [comment]
I just verified `up` and `VK_UP` are working as expected by starting an instance of MCE Controller on one laptop ("Client on port 5150") and another instance on another PC ("Server, listening on port 5150").

```
2020-03-29 13:49:37,121 INFO  - SocketServer: Received from Client #1 at 192.168.1.118:50648: VK_UP
2020-03-29 13:49:37,126 INFO  - SendInputCommand Cmd="VK_UP" Args="" Vk="VK_UP" Shift="False" Ctrl="False" Alt="False" Win="False" (vk_UP) (0x26)
```

This resulted in my cursor moving up once in the window it was in on the "Server" pc, as expected.

I did the same thing using `down` and it worked as expected.

I'm not sure what problem you are reporting.

Can you clarify?

What Control4 driver are you using?

**Comment by shutupdude** [comment]
I am using Gary Newman's driver on my c4 project. I just installed your latest version and now it is working. Before I felt like it was working intermittently between different types of programs. For example I could navigate file folders as you would naturally expect with the sr260, but I didn't have control over Steam Big Picture mode. However, now it is working as expected with the `VK` commands. Now with that working, I'm looking forward to making quick launches for when I switch to my desktop and fire up Big picture mode all in one go. Take care! Stay safe.

**Comment by tig** [comment]
Please tell me more about gary newman's driver. I'm not aware of that!

**Comment by shutupdude** [comment]
You bet:

https://github.com/garrynewman/Control4.MceControllerDriver

I dropped this into my home project, and pointed it at my computer running MCEC. From there I can hit buttons on my sr260 and your amazingly verbose log will pick it up. It even see's when the zigbee node goes to sleep. Here's something interesting too: when hitting the coloured programmable buttons, the log would show `vk` codes that are not typical. For the blue button the log shows `vk_program_d` and just the same I put that virtual key into `MCEControl.commands` and it fires my custom commands! What a great project.

**Comment by tig** [comment]
This is cool.

I'll give it a try.

He's basically taking commands sent by the `MEDIA_PLAYER` proxy and forwarding them to MCE controller, prefixing with `VK_`:

    socket:Write( "VK_" .. strCommand .. "\r" );

This is why you're seeing all the commands. I may fork his driver and update it. If I do, I'd probably change this code to:

    socket:Write( "C4cmd_" .. strCommand .. "\r" );

In order to make it clear these are Control4 commands and not virtual key-codes.

**Comment by shutupdude** [comment]
That would be awesome!
