### ISSUE TITLE
Middle Mouse Button

### ISSUE THREAD

**Issue by hotelfoxtrotnovember** [tig/mcec#16]
How do you send middle mouse button commands?  The left and right button commands work great.  I've spent some time playing around with the `xbc`, etc. commands, but the behavior I'm seeing just isn't what I'd expect (trying to open a link in a new tab in a browser, it instead acts as if I hit the Back button).  I tried both `mouse:xbc,3` and `mouse:xbc,1`, but both did the same thing.  Thanks!

**Comment by tig** [comment]
I don't know if `xbc` etc... ever worked.

Looking at the docs there is direct support now for middle button, in the same way `lb*` and `rb*` are supported. So I just implemented that for `mb*`. 

https://github.com/tig/mcec/releases/tag/v2.2.6.3

Let me know if it works. I'll update the docs later.

Note the `xbc` stuff probably is useless for anything.

**Comment by hotelfoxtrotnovember** [comment]
That worked, thanks!
