### ISSUE TITLE
Enabling Commands

### ISSUE THREAD

**Issue by wayner9** [tig/mcec#17]
When you try to use MCE Controller you get a message like:

2020-12-20 23:40:52,508 INFO  - Command: Attempt to execute a disabled command (ch-)
2020-12-20 23:40:52,511 INFO  -          As of MCE Controller v2.2.1 commands are disabled by default.
2020-12-20 23:40:52,513 INFO  -          Edit MCEControl.commands to enable commands (change `Enabled="false"' to 'Enabled="true"').

I didn't notice anything in the documentation about this.  Why were all commands disabled?  Presumably for security but by default nothing works and it seems kind of painful to go through and enable every command.

What's the easiest way to enable all commands?  Do a replace('enabled="false"','enabled="true"') in the MCEControl.commands file or will that hose something else?

**Comment by tig** [comment]
Yes, it is for security. Sorry it’s a pita. It is documented here:

![image](https://user-images.githubusercontent.com/585482/102803504-308d6080-436d-11eb-88af-c3ec5629949b.png)

I remembered that I did SOMETHING to enable all of them. 
 
![image](https://user-images.githubusercontent.com/585482/102803513-3420e780-436d-11eb-90d3-0059f5f3e2cd.png)

So… open your .commands file and delete the “Version” attribute. Re-run MCE Controller. 
 
![image](https://user-images.githubusercontent.com/585482/102803530-397e3200-436d-11eb-8c36-6bb08ee23936.png)

Let me know if this works!

**Comment by wayner9** [comment]
Thanks Charlie - that worked.  But it gives a bit of a confusing message when it starts up:

"MCEControl.commads was created with a legacy version of MCE Controller.
Converting it and enabling all commands it contains."

Shouldn't it say "Converting it will enable all commands that it contains."

**Comment by tig** [comment]
> Thanks Charlie - that worked. But it gives a bit of a confusing message when it starts up:
> 
> "MCEControl.commads was created with a legacy version of MCE Controller.
> Converting it and enabling all commands it contains."
> 
> Shouldn't it say "Converting it will enable all commands that it contains."

No, I think the wording is correct as the log entry is describing what MCE Controller was actually doing:

- Converting it to the most recent schema
- Enabling all commands

Normally this code would only run if someone upgraded MCE Controller from a pre-whatever-version-didn't-have-version info.
