### ISSUE TITLE
Disable Auto Update Notification

### ISSUE THREAD

**Issue by sensai761** [tig/mcec#19]
The Auto update pops up a notification box on top of all windows currently and cannot be disabled. 
It would be nice to have a check box in the settings menu to disable this feature. 
I have unattended computers generating a video displays connected to an automation system and that system is using these commands to change between a fixed number of commands. These computers are configured to auto reboot and go back to where they were on startup or power failure. I suspect that on reboot this auto update check is happening and it is generating a service request to remove the popup box.

This little piece of software has been a great help to me over the years, Thanks.

**Comment by tig** [comment]
That should be an easy fix. I'll look at it asap.

**Comment by tig** [comment]
Ha! I'm no dummy; I just have a bad memory.

Support for disabling the update dialog is already there. It's just that there's no UI for it and I didn't document it.

In `MCEControl.settings` change

```
  <DisableUpdatePopup>false</DisableUpdatePopup>
```

to

```
  <DisableUpdatePopup>true</DisableUpdatePopup>
```

And restart MCE Controller. You'll no longer get popups.

**Comment by sensai761** [comment]
Awesome, Thanks!
