### ISSUE TITLE
Feature Request: Removing TCP/IP Server & Client Monitoring

### ISSUE THREAD

**Issue by briangun1** [tig/mcec#20]
I'm designing a Crestron-based RS-232 control system, and am looking to install MCEC to monitor for serial commands. The TCP/IP features will cause MCEC to be flagged by the client's network security team, so I'm requesting a version of MCEC with only serial monitoring capability.

**Comment by tig** [comment]
Hi Brian,

Simply ensure the "Enable Client" and "Enable Server" checkboxes are unchecked. All TCP/IP functionality will be disabled.

![image](https://user-images.githubusercontent.com/585482/119709973-b0cf5a80-be12-11eb-829c-4447e79297d9.png)

![image](https://user-images.githubusercontent.com/585482/119709995-b4fb7800-be12-11eb-859b-c22183d52e6d.png)

**Comment by briangun1** [comment]
Great. Is there a way to disable the TCP/IP server by default? As of right now it is enabled when you install the application.

**Comment by tig** [comment]
Sort of:

Settings are stored in `%USERPROFILE%\AppData\Roaming\Kindel Systems\MCE Controller\MCEController.settings`. It is an XML file.

If you were to 

1. Create a `MCEController.settings` file that looked like this:

```xml
<?xml version="1.0" encoding="utf-8"?>
<AppSettings xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <ActAsClient>false>/ActAsClient>
  <ActAsServer>false</ActAsServer>
</AppSettings>
```

2. Install MCE Controller
3. Copy the `MCEController.settings` file above into   `%USERPROFILE%\AppData\Roaming\Kindel Systems\MCE Controller\`
4. Run MCE Controller, both client & server would be disabled.

Will this work?

**Comment by briangun1** [comment]
That solution hopefully should satisfy them. Does the `MCEController.settings` file get overwritten once a user checks the box to enable the client / server?

**Comment by tig** [comment]
IIRC it gets written whenever ok is pressed in the settings dialog and when app exits (to save window post).

-cek
Via mobile; expect brevity, typos, and dangerous driving.

________________________________

**Comment by briangun1** [comment]
That seems to be correct - I made the file read-only and that's when the errors popped up. I think this will work for our purposes. Thanks!
