### ISSUE TITLE
Passing URL via RS-232 with MCEC

### ISSUE THREAD

**Issue by briangun1** [tig/mcec#21]
We'd like to pass a unique URL from Crestron to the PC via RS-232 and open up a web browser with the passed URL. Are you aware of any way to accomplish this via your program? Thanks!

**Comment by tig** [comment]
There's probably a few ways to do it. The first that comes to mind is to use send these commands:

`shiftdown:winl` to do the equivalent of holding the Win key down
`chars:r` to press the r key
`shiftup:winl` to lift the Win key
might need to delay
`chars:<url>` to type the URL in the run dialog
`VK_ENTER` to do it.

Let  me know if this works!
