### ISSUE TITLE
Overriding TimeOut on Shutdown Command doesn't seem to work

### ISSUE THREAD

**Issue by kstangel** [tig/mcec#22]
I've attempted to override the TimeOut on the Shutdown command  to 5 and it appears to take the change but when executing the command the log shows the TimeOut="30" and then it takes 30 seconds before the shutdown is executed. I even attempted to make my own command and had the same issue.

**Comment by tig** [comment]
I'll look later today. Thanks.

-cek

Sent via mobile. Expect brevity, typos, and dangerous driving.


________________________________
From: Kyle Stangel ***@***.***>
Sent: Wednesday, June 2, 2021 12:29:14 PM
To: tig/mcec ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [tig/mcec] Overriding TimeOut on Shutdown Command doesn't seem to work (#22)


I've attempted to override the TimeOut on the Shutdown command to 5 and it appears to take the change but when executing the command the log shows the TimeOut="30" and then it takes 30 seconds before the shutdown is executed. I even attempted to make my own command and had the same issue.
