### ISSUE TITLE
Windows 7 support

### ISSUE THREAD

**Issue by sheppy99** [tig/mcec#23]
Is there an easy way to use V2,x with Windows 7 MCE?
I've got V 1.9 currently and am experimenting with ways to get data between OpenHAB and Win7 Media Center. So far I've used it with Expect Lite to connect, issue a command and then disconnect. Ideally I'd like to make this 2 way so that pressing the Green Button on the MCE remote or play sends a command to OpenHAB. Alternatively is there a way of sending status messages to a rest interface? Also have you considered offering MQTT as an interface between Windows and the outside world? That would make interfacing with home automation a breeze.

**Comment by tig** [comment]
Sorry, I no longer have access to any Win7 machines to test this on.
