### ISSUE TITLE
Can't run "Metro" apps or Windows 10 apps

### ISSUE THREAD

**Issue by wayner9** [tig/mcec#4]
I am trying to set up  a command to start the Netflix Windows10 app.  From a command line, or as a desktop shortcut the following works: "C:\Windows\System32\cmd.exe /c start netflix:"

So I have added the following line to my commands file:

<StartProcess Cmd="netflixw10" File="C:\Windows\System32\cmd.exe /c start netflix:"/>

But it doesn't work.  I get the following error:
error:  System.ComponentModel.Win32Exception (0x80004005):  The system cannot find the file specified at ...

Anyone know the syntax to launch these types of apps with MCEC?

**Comment by tig** [comment]
Try this:

```
     <StartProcess Cmd="netflix" File="shell:AppsFolder\4DF9E0F8.Netflix_mcm4njqhnhss8!Netflix.App" />
```
