### ISSUE TITLE
Hi ! I love the MCEC controller, but is not a BUG, I just need to know if is possible to have some feedback to the client.....for example I send the command, but I don't know if is esecuted. In my application I'm increasing the volume level....the must could be to receve the feedback with the number of the volume level....

### ISSUE THREAD

**Issue by lightware22** [tig/mcec#40]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version Information**
Include the first line from the log window, like this:
```
2020-03-29 16:42:20,435 INFO  - MCE Controller v2.2.3.2 - OS: Microsoft Windows NT 10.0.18363.0 on x64 - .NET: 4.0.30319.42000
```

**Snippets from the log**
Include any other relevant logs (either copy/pasted from the MCE Controller window or from the log files found in `%appdata%\Kindel Systems\MCE Controller` which contain more debug info).

```
Paste Logs here.
```

**Desktop (please complete the following information):**
Details of home control system you are interfacing with.

**Additional context**

**Comment by tig** [comment]
I don't think so. Sorry.
