### ISSUE TITLE
MCEControl.commands location - move to %APPDATA%?

### ISSUE THREAD

**Issue by wayner9** [tig/mcec#6]
The commands files is stored in the same folder as the exe which is likely:

C:\Program Files (x86)\Kindel Systems\MCE Controller, or
C:\Program Files\Kindel Systems\MCE Controller

Isn't it now frowned upon to store config files in this location?  Therefore shouldn't this file be stored in the %APPDATA% folder - just like the settings file.

**Comment by tig** [comment]
V2 Beta 2 addresses this:

If mcecontrol.exe is run from the \Program Files directory where the installer put it, the .settings, .commands, and .log files will be accessed from %APPDATA%.

If mcecontrol.exe is run from any other directory, that directory will be used for the .settings, .commands, and .log files.

I'll be uploading the Beta 2 release soon.

**Comment by tig** [comment]
Fixed in v2.
