### ISSUE TITLE
startProcess command

### ISSUE THREAD

**Issue by RomaMul** [tig/mcec#7]
How can i start some file (exe,bat) with startProcess command ?
I create MCEControl.commands file with this command:
"<StartProcess Cmd="test" File="C:\Install\Offline 08-02-2019\index.html" />"
When i try to send "test" command i get this error "Cmd: Unknown Cmd: test"
I work with win 10.
Another question, how can I kill process with software name ?
Thank you,

**Comment by RomaMul** [comment]
this command
StartProcess Cmd="test" File="C:\Install\Offline 08-02-2019\index.html"

**Comment by tig** [comment]
In the current version the value of File must be a program name that is either in the PATH or fully qualified. File associations are not supported.

I'm working on fixing this right now in v2.

**Comment by tig** [comment]
This is now working in v2. For example, I created these commands:
```
<StartProcess Cmd="code" File="code" />
<StartProcess Cmd="tada" File="C:\Windows\Media\tada.wav" />
````
And they work as expected. 

I'll be adding an updated Release for v2 soon.

**Comment by tig** [comment]
Fixed in v2.
