### ISSUE TITLE
Trouble getting old commands to work with new MCE version.

### ISSUE THREAD

**Issue by GasTurbineMan** [tig/mcec#8]
Just installed the newest version 2.0.5 over the older 1.x version which had been working great.  I have a Windows 10 system.  The new version over-wrote my original mcecontrol.commands file with what appears to be a newer format MCEControl.commands.  I attempted to add my custom commands from my original file to the new file, but I continue to get an "unknown command" error in MCE activity window.  Will attach both files.  Please advise on how to add my custom commands to the new format file.  Thanks.

[MCE Commands.zip](https://github.com/tig/mcec/files/3746832/MCE.Commands.zip)

**Comment by tig** [comment]
Looking into it now...

**Comment by tig** [comment]
Try this version and please let me know if it fixes the issue. I had a really stupid bug. My apologies. 

[MCEController Setup.zip](https://github.com/tig/mcec/files/3746920/MCEController.Setup.zip)

**Comment by GasTurbineMan** [comment]
[MCEControl.log](https://github.com/tig/mcec/files/3747803/MCEControl.log)

The latest version is working better, but still not there it seems.  The good news is that my client app (Home Remote) will now open the 2 apps on my Windows 10 PC (NextPVR and HDHomeRun) and I seen where the new commands are added.  But then the button commands still don't work - giving a new error that what we were getting.  One other minor thing I noticed is an error regarding not being able to check for a new version.  I appreciate your help on this.  Attached is my most recent log.

**Comment by tig** [comment]
Fixed in v2.0.6.42 which is now the latest Release download.

**Comment by GasTurbineMan** [comment]
Yes, my initial but brief testing of v2.0.6.42 appears to work as expected.  Many thanks!
